# Please update Haskell image versions under .github/workflows/ci.yml together to use the same GHC version
# (or the CI build will fail)
resolver: lts-22.43
pvp-bounds: both
packages:
- '.'
ghc-options:
  # Build with advanced optimizations enabled by default
  "$locals": -O2 -Werror
extra-deps:
# As of 2021-11-08, the latest release of `language-javascript` is 0.7.1.0,
# but it has a problem with parsing the `async` keyword.  It doesn't allow
# `async` to be used as an object key:
# https://github.com/erikd/language-javascript/issues/131
- language-javascript-0.7.0.0
# Fix issue with libtinfo.
# See https://github.com/purescript/purescript/issues/4253
- process-1.6.13.1
# The Cabal library is not in Stackage
- Cabal-3.10.3.0
# hspec versions 2.9.3 to 2.10.6 depend on ghc
# ghc depends on terminfo by default, but that can be ignored
# if one uses the '-terminfo' flag.
# Unfortunately, hspec doesn't expose a similar flag.
#
# Using hspec >= 2.10.7 addresses this.
- hspec-2.10.9
- hspec-core-2.10.9
- hspec-discover-2.10.9
- bower-json-1.1.0.0
- haskeline-0.8.2
- these-1.2.1

- github: Vekhir/aeson-better-errors
  commit: 1ec49ab7d1472046b680b5a64ae2930515b47714

- github: MercuryTechnologies/cheapskate
  commit: 30ca0ccbac2f59bedf89a855627373931a7e3758

- github: GuillaumedeVolpiano/pattern-arrows
  commit: 785512b896b0c20c576cbbd099f705798117801c

nix:
  packages:
  - zlib
  # Test dependencies
  - nodejs
  - nodePackages.npm
  - nodePackages.bower
flags:
  aeson-pretty:
    lib-only: true
  haskeline:
    # Avoids a libtinfo dynamic library dependency
    terminfo: false

allow-newer: true
allow-newer-deps:
  - aeson-better-errors
  - cheapskate
  - haskeline
  - process
